YAML
name: CI

on:
  push:
    branches: [ "principal" ]
  pull_request:
    branches: [ "principal" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar e Buildar
        run: |
          npm install
          npm run build
